### PR TITLE
Update about.html

### PR DESCRIPTION
**Pull request by rschlosser0205**
Update roles & names. Update link to github and slack

### CODE REVIEW

**Comment by justinnhli** [comment]
LGTM. This would also be a good chance to establish update/publication procedures for the website, if there should be one. Thoughts on this process, @DyaniDillard @Joey-Rose?

**Comment by Joey-Rose** [comment]
@justinnhli like a guide telling you how to add stuff to the website/this repo? Or figure out who's gonna review all the PRs and all that jazz?

**Comment by justinnhli** [comment]
I was thinking more the latter. I'm happy to review them, but the club might want to take over that responsibility as well.

**Comment by Joey-Rose** [comment]
Okay. I'd be fine with the project lead for this website to take over that responsibility. Thoughts on this, guys?

**Pull request merged**
